### PR TITLE
configure.ac:

### PR DESCRIPTION
**Pull request by sedwards**
config.h.in:
lib/gftp.h:
  check for sys/sysmacros.h

sockutils.c: avoid socket blocking in gftp_fd_set_sockblocking when running on macOS

listbox.c: avoid crash during listbox creation on macOS

### CODE REVIEW

**Comment by sedwards** [comment]
Both of these are kind of hacks. 
I tested ssh/scp and without disabling the sockblocking functions it gets an ioctl error on macOS.
The listbox creation error seems to actually be due to a bug in gtk-quartz.

**Comment by wdlkmpx** [comment]
Looks good to me.

When I edit a single file, I include the file name in the commit title (or something).
When I edit several files within a directory, I include only the dir name (e.g. src/gtk)

I think the commit title (the first line in the commit msg) should be: `fixes / hacks for macOS`

In the `macOS` branch, run `git commit --amend` edit text and then force-push the change (git push -f), you might also want to specify what macOS version you are using.

On linux gftp compiles in old distros (ubuntu precise, slackware 14.0) - 2011-2012.

**Comment by wdlkmpx** [comment]
Or if you want I can do the change for you and add the commit to the master branch but the commit hash will be different, and the PR will be closed.

**Comment by sedwards** [comment]
Thanks. I updated the commit, is this how you would like it?

fixes / hacks for macOS

configure.ac: check for sys/sysmacros.h
sockutils.c: avoid socket blocking in gftp_fd_set_sockblocking when running on macOS
listbox.c: avoid crash during listbox creation on macOS

**Pull request merged**
