### PR TITLE
restore FSP support

### PR DESCRIPTION
**Pull request by wdlkmpx**
use only fsplib.c + fsplib.h
and FSP_NOLOCKING

Reverts "remove FSP support (#35)" da2ee474bda1e3fde5aec50c25c8121fad56511c

### CODE REVIEW

**Comment by wdlkmpx** [comment]
I've been playing with libfspclient (fsplib) and I'll include the edited code in gftp, so that it keeps being the only known app that supports FSP. An asset
https://github.com/wdlkmpx/libfspclient/commits/master

I'm also editing the server, hopefully one day the issues will be resolved

I'll update and merge this PR...

**Comment by hsn10** [comment]
fpsd server should work, but i didn't tested it with newer GCC. Last version I tested passed test suite.

**Comment by wdlkmpx** [comment]
There is a problem with fspd, I don't know how to grant permission to upload files to the server. No matter what I do, all I get is Operation not permitted.

I've been reading the code, and config file but I'm not sure where to set the passwd, this is a flaw, it shouldn't be that hard to grant write permissions... I think this needs fixing

It also needs several cleanup operations like this:
https://github.com/wdlkmpx/fsp/commit/b388fd82cce9cf65ee812997a883c398bdf3a59b

**Comment by wdlkmpx** [comment]
The FSP client works OK in gftp if you only need to download files and browse directories. I think it was truly broken sometime ago, that's why I removed it, but the situation has improved, probably a side effect of other fixes elsewhere.

Now, the problem is properly configuring fspd to allow write operations on the server, I've tried all sorts of settings but nothing works, this a bug on the server side of course, that requires a fix or a change in design to reduce broken or obscure security measures

All of this can be discussed if you wish, it's all about simplifying things

I'm also adding Windows support to libfspclient (MinGW), but currently I can only test on Wine, compiles but needs work, I'm not sure if it will be finalized..

**Comment by hsn10** [comment]
to allow write support for directory file **.FSP_OK_ADD** must be there **and** _fspd_ must run in _read-write_ mode.

**Comment by hsn10** [comment]
r/w mode can be checked in _fspclient_ (i dont have classic fsp cli installed).

$ fsp
fsp> open 127.0.0.1 8080
fsp> ver
[...]
readonly: **no**

**Comment by wdlkmpx** [comment]
OK, now the server apparently allows uploading files, but the transfer fails, this is probably a bug in gftp or fsplib, this will take some time to fix

Now I added these files:
- .FSP_MAKEDIR_OK
- .FSP_MKDIR_OK
But I still can't create directories... Operation not permitted

What do you mean by classic fsp client? I don't see an FSP client in the FSP source tree, there is fxxxcmd, a lot of CLI apps that are installed, some of them with questionable names: fget
The thing is none of those apps seem to work with the expected parameters

While I was playing I unified and simplified the whole thing: fspcmd
https://github.com/wdlkmpx/fsp/commit/6beeff0c0c47538b8a4708f7c0f7b693f4b20e0d

**Comment by hsn10** [comment]
man _fspd_ its _.FSP_OK_MKDIR_

**Comment by wdlkmpx** [comment]
Ok reading the manpage now, alien stuff, like Aliens vs Predator: Requiem

Haha yeah I actually created both .FSP_OK_MKDIR and .FSP_MKDIR_OK. And .FSP_OK_DEL and .FSP_OK_RENAME

But it still doesn't work, I cannot create a directory/rename a file/delete a file, this is a bug, where?

I added .FSP_OWNER (fstpd.conf: `permit_passwordless_owners on`)
... still doesn't work

At least the upload bug seems to be related to how gftp handle things, errors with the local filesystem. That's definitely a gftp bug.

I realize that design is clever, with the correct info different people have access to different parts of the the directory tree. But time waits for nobody, The year is 2021.

The C clients or apps require an alias or something? fspmerge or fspcmd seems to be the prototype for the C client, but they never implemented in C I guess.

This is what I think about the fsp package:
- Need to get rid of the many CLI apps (don't know how they work), implement the unified client instead
- make fspd more similar to ftpd servers without flag files, everything in config file
- store directory listings and stuff in /tmp/..., to avoid using the same directory for special purposes

Maybe a new user type with write access assigned by ip: 127.0.0.1 W 
or a password

Maybe just like simple anonymous ftp servers, global mkdir, rename, del, upload, options.

**Comment by wdlkmpx** [comment]
I needed to get some server info, so I had to fix fspcmd, https://github.com/wdlkmpx/fsp/commit/601d7663746ad01bd0f40acb876ab1e74467d4da

In the root directory, I have all the .FSP_OK_* files, but the server says that no write operation is allowed

```
# export FSP_HOST=localhost
# export FSP_PORT=21
# ./fspcmd pro /
/
owner: other, del: N, create: N, mkdir: N, get: Y, list: Y, rename: N.

# ./fspcmd ver
Remote FSP version: fspd 8.1b25
	Logging of all server transactions is ENABLED.
	Remote server is run in READ/WRITE mode.
	Server DOESN'T REQUIRE connections to reverse.
	Remote server is run in PUBLIC mode.
	Remote server throughput control is DISABLED.
	Server can process extra data in input packets.
	Max. payload size supported by server is 1452 bytes.
```

Some routine may be broken or misbehaving. This issue has been present since day 1, so it shall be fixed one way or another. My method is the Gnome method, fix bug, delete feature... fix all bugs, delete all features

**Comment by hsn10** [comment]
I have fspd b29 root set to /tmp tmpdir /tmp/fsp
I do touch /tmp/.FSP_OK_ADD and it shows add: yes
OS: Freebsd 12.1

**Comment by wdlkmpx** [comment]
I still have the same issue, I guess it's linux-specific. It will take some time to fix.

Now reading the manpages and the old FAQ, it seems to me that other FSP clients were probably better designed (FTP-like) and worked properly, but all links are dead. The one in the FSP package is ... weird to say the least and at least these 2 commands can be deleted:
- fspcmd_hostcmd.c
- fspcmd_setup.c
They need compiled LEX scripts and were used in the golden FSP era, where you stored many shell scripts in directories (I guess?) containing exported variables or something .. this doesn't really make sense now. The whole thing,really, but specially those 2 commands.

The new FAQ should be a text file in markdown format, to avoid all the JADE stuff. To reduce the number of overall dependencies to check. Portability level: over 9000.

I could go on and on explaining what I think, but of course I'm just doing what I want, it's a game.

**Comment by wdlkmpx** [comment]
When it comes to portability, I realize that the apps might not support big endian machines. This is not a problem when you use plain text for everything (IRC style), CMD text args, REPLY text args. No ipv6 support, it's probably not that hard to add it.

So we're dealing with ancient stuff and it's hard to bring it to modern times, but what I'm doing makes 100% sense... attempting to convert fspcmd into a true client. Bookmarks? Probably another app that uses the client library i.e. gftp.

There are thousands of dead apps and protocols, and FSP is one of them, what I'm doing will probably bring it back, in a zombie state... simpler, usable, no need to read 60 manpages to understand how basic things works. It's also fine to ignore it, that won't prevent me from chopping the code until everything works as expected... the same thing will happen to gFTP.

**Comment by wdlkmpx** [comment]
You're right, the flag files do work. I changed the settings many times to see if commands work and ended up disabling access files. I enabled and disabled that setting several times, so I was doing something wrong.

The search is over, the setting was right before my eyes.

Sorry for the trouble, but it just shows how weird the whole thing is, there's a reason it faded into obscurity..

**Comment by wdlkmpx** [comment]
Overall FSP support in gFTP seems OK, but transfers do not start immediately, you have to wait.

With some effort this can happen:
```
Could not get FSP directory listing /raspi: Success
Successfully changed local directory to /initrd/mnt/dev_save/git/gftp
* fspd 2.8.1b30
Error: Cannot upload file /raspi/COPYING
Could not download /initrd/mnt/dev_save/git/gftp/COPYING from local filesystem
Error: Remote site local filesystem disconnected. Will reconnect in 30 seconds
```
After some activity - uploading/downloading/browsing directories, bugs may start to appear. I also got `Operation canceled` after each successful chdir.

To debug this and the FTP stuff as well, I might have to add debug code to everything. gFTP is modular and allows plugins, but with several modules interacting, it gets harder to figure out where and when things go wrong.

**Comment by hsn10** [comment]
Do You have locking enabled?

**Comment by wdlkmpx** [comment]
I get the same results with locking enabled, but this message
`Error: Cannot upload file /raspi/COPYING`
is triggered by fsp_canupload() when the client doesn't have write access to the directory.. but the message doesn't tell you why

The other gftp messages are a bit confusing as well, since both Local and Remote sites .. can be remote sites (Window 1/2), powerful design, but it just confuses me

My advice is that you clone my repos and continue with that codebase, The only problem is that libfspclient no longer has scons stuff, but it's easy to restore it, but it's possible to use a simple configure script with 0 dependencies, like this:
https://github.com/wdlkmpx/unace1/blob/master/configure

I have ideas about possible changes and cleanup operations that can be briefly discussed in issues

**Comment by wdlkmpx** [comment]
There should be a global option to set write access to everything.  You can create a directory, but you're not allowed to modify that dir.

I think FSP support was always in an alpha state, since at least the mkdir command expects a full path perhaps, all dirs are always created in the root dir, I guess the code expects something like CWD to set the current dir

At this point FSP would only make sense if it's as simple as the busybox ftpd implementation and some updates to the socket stuff

With FTP, gFTP can handle files like a true file manager, with FSP... it needs fixes... in both gftp and the fspd code. The FSP stuff should be reassessed, but I don't there's enough time and motivation to discuss it

FSP would only make sense as an FTP protocol for UDP, basically the same protocol with some tweaks for UDP connections.

**Pull request merged**
