### PR TITLE
use GtkUIManager instead of GtkItemFactory

### PR DESCRIPTION
**Pull request by wdlkmpx**
GtkItemFactory  = gtk1

### CODE REVIEW

**Comment by masneyb** [comment]
I'm going to hold off on merging this until a fix is available for those two issues. The `#if 0` checks will need to be removed before this is merged into master.

**Comment by wdlkmpx** [comment]
The #if checks hide 3 features that are not implemented with GtkUIManager

- Window1/Window 2
- Ascii/Binary
- Bookmarks dynamic menu (so far it looks like a major headache)

And 1 feature that was also broken with GtkItemFactory

- Enable/disable menu items: I fixed it to work with GtkUIManager (it
didn't work with GtkItemFactory) but applying the old logic it
disables the transfer menu items even when a transfer is happening.

So that can be removed.

**Comment by wdlkmpx** [comment]
- Ascii/Binary - fixed.. already an option in Preferences->FTP dialog... is that ok? I don't know.. it's up to you to decide if something is right or wrong.

- Window1/Window2.. see issue, I don't think I'll ever find the courage to learn how to restore this in the menu.. any comments?

- Bookmarks dynamic menu.. this will take some time

- It is ok to remove partially broken code that I'm not interested in fixing completely?

**Comment by wdlkmpx** [comment]
I guess I don't know how to make gtkUIManager create dynamic submenus and menus. Nothing I try works

But adding stuff manually I'm having some positive results, but only with extra menu items.. that I can only add to gtkUIManager popup menus because they're toplevel menus, unlike the menus in the main menubar.

Something like this:

```diff
diff --git a/src/gtk/bookmarks.c b/src/gtk/bookmarks.c
index a4fc2f2..b8d4eb9 100644
--- a/src/gtk/bookmarks.c
+++ b/src/gtk/bookmarks.c
@@ -53,6 +53,12 @@ run_bookmark (gpointer data)
   ftp_connect (current_wdata, current_wdata->request);
 }
 
+void
+on_menu_run_bookmark (GtkAction *action, gpointer data)
+{
+  run_bookmark(data);
+}
+
 
 static void
 doadd_bookmark (gpointer * data, gftp_dialog_data * ddata)
@@ -152,31 +158,30 @@ add_bookmark (gpointer data)
 void
 build_bookmarks_menu (void)
 {
-#if 0
-  GtkItemFactoryEntry test = { NULL, NULL, NULL, 0, NULL, NULL };
-#endif
+  gchar *action_name;
+  const gchar *label;
+  GtkAction *action;
+  GtkWidget *bmenu = gtk_ui_manager_get_widget(factory, "/L");
+
   gftp_bookmarks_var * tempentry;
 
   tempentry = gftp_bookmarks->children;
   while (tempentry != NULL)
     {
-#if 0
-      test.path = g_strconcat ("/Bookmarks/", tempentry->path, NULL);
-      if (tempentry->isfolder)
-        {
-          test.item_type = "<Branch>";
-          test.callback = NULL;
-        }
-      else
-        {
-          test.item_type = "";
-          test.callback = run_bookmark;
-        }
+      action_name = tempentry->path;
+      label = tempentry->path;
+      action = gtk_action_new(action_name, label, NULL, NULL);
+      if (tempentry->isfolder) {
+         //create submenu..
+      }
+      else {
+        gtk_menu_shell_append (GTK_MENU_SHELL (bmenu),
+                              gtk_action_create_menu_item (action));
+        g_signal_connect(action, "activate", G_CALLBACK(on_menu_run_bookmark),
+                        (gpointer) tempentry->path);
+      }
+      g_object_unref(action);
 
-      gtk_item_factory_create_item (factory, &test,
-                                    (gpointer) tempentry->path, 1);
-      g_free (test.path);
-#endif
       if (tempentry->children != NULL)
         {
           tempentry = tempentry->children;
```

Screenshot

Adding submenus probably requires a linked list with pointers to created menus and stuff so that menu items can be added.

I guess I can do everything again in a different way, but of course all the GtkUIManager commits will remain because they show how to port GtkItemFactory to GktUIManager  .. and everything is deprecated .. and

**Comment by wdlkmpx** [comment]
I was expecting some comments but I figured out I should reimplement everything

I addressed all the issues. The level of complexity is a bit high, and I imagine future devs suffering trying to upgrade to the next api version, which I read is less powerful.

GtkItemFactory has been completely replaced by GtkUIManager while keeping the same behavior and functionality.

**Comment by wdlkmpx** [comment]
While rebasing I ended up adding some outdated wip diffs, I corrected the affected commits again, I only deleted on line:

```// unimplemented menu items in gtkUIManager...``

**Pull request merged**
