### PR TITLE
Update Dutch translation (nl.po). Fix spelling error.

### PR DESCRIPTION
**Pull request by MPolleke**
Update Dutch translation (nl.po). 
Fix spelling error.

I think I did everything right with the po file, but some strings are not visible here. I have the same with another application so probably it is my install. Could you test if all strings show as translated?

Thank you for maintaining gFTP.
Regards, Marcel Pol

### CODE REVIEW

**Comment by wdlkmpx** [comment]
Thanks for your translation, Ok, I'll test.

 Did you use po/gftp.pot or did you generate the file, or how did you perform the updates?...

You might want to revise that translation in a few months, as some large changes may happen assuming that I haven't lost all the GTK knowledge I gained in 2020. The most important thing to know is how stable the app is according to feedback from users

**Comment by MPolleke** [comment]
Hi, thank you for your response.
I think I did it all right with a new pot. It is just that some strings do not get picked up, but I have the same with a different gtk program, so I would think it is a local problem. If it works for you it's fine :)

No problem for updates coming :) I hope to be able to update nl.po again.
I do seem to have some issues with 2.7.0b while compiling it with all the configure flags from my rpm distro. I hope to be able to provide some bug reports that make sense :)
I always very much like gFTP 2.0.19, but due to some bugs I switched to filezilla. That has gained a reputation for malware, and I am looking forward to using gFTP more.

Have a good week.

**Comment by wdlkmpx** [comment]
You're right, your changes are correct but some strings are not being translated.. the Menu. I'll merge this then I'll fix the issue
NL

**Comment by wdlkmpx** [comment]
Commit e819630bb622f77cef1c6691409f72a35f2b4563 fixes the translation of menus.

I was having this compile error: `initializer element is not constant`

And I was trying all kinds of esoteric code to make it work. I was going mad, but found the solution.

# LANG=nl_NL.utf8 gftp
nl

**Comment by MPolleke** [comment]
Thank you, that works wonderfully :)

**Comment by wdlkmpx** [comment]
Yeah I also used to use filezilla, but gftp is usable now, I mean, it has less bugs and it's a bit more stable perhaps. And it still supoorts ancient distros, so it's the universal FTP client for unix systems.

But as everything that is written in C & GTK, it's quite hard to maintain and improve. But it compiles in 10 seconds.

It seems to me that some advanced features and multi transfer stuff don't work quite right, so if you connect to a server, start a download, disconnect, connect to another and queue a download or something... something not really good happens, I'm not sure. It's been months since the last time I performed some tests.

I'll split some files, i.e: bookmarks.c + bookmarks_edit, gftp-gtk_menu, to make stuff more readable for me and for others, showing working examples of how to do GTK things, there are many gotchas. This affects translations, but I think it's possible to update the most recent ones with:
- ./autogen.sh
- ./configure --prefix=/usr
- make -C po update-po

- open `po/nl.po` with a text editor (don't close or refresh contents)
- run `git clean -dfx` to clean to source tree
- (in your text editor) save nl.po again,
- `git diff` will show what has changed, and you can review and proceed to fix some possible issues.
- a new pull request is ready

**Comment by wdlkmpx** [comment]
I forgot to add `git checkout -- .` after git clean -dfx ...

I created a Wiki page where the juicy secrets of how to update translations have been finally revealed to the general public.

https://github.com/masneyb/gftp/wiki/How-to-update---create-translations

**Comment by MPolleke** [comment]
Thank you.

Yes, I had already seen some funky stuff. I had it set to use a single connection. Upload a file, and wjile that is running click on a file and download. Suddenly the remote list disappears. The first file still goes through, but I don't know about the second one :) And it disconnects.

Most Linux distro's still carry 2.0.19. Would it be worthwhile to request updates and draw some attention? Or is that way too early yet and unwanted? Just wondering.
Many distro's are also having plans to drop gtk2, but I think only Arch Linux is busy working on that.

**Comment by wdlkmpx** [comment]
Arch, Debian Testing, Slackware Current and a few other distros are using 2.7.0b.
https://repology.org/project/gftp/versions

Well, most of the changes are basically GTK updates to get rid of GTK1 cruft and make the GTK3 por compile, but that is not finished yet, it needed some extra changes and my attention diverted to something else. Making a pure GTK3 port without deprecations will be almost as hard, and perhaps the bookmarks menu should be removed.. connect to server from the bookmarks dialog. Replacing the GTKUImanager dynamic stuff will be H.A.R.D.

If only gFTP also had support for MS Windows (mingw32), we'd have many more people looking and potentially contributing.

Well, I find the 2.0.19 unusable, so it's better to draw attention to this version. This is upstream, not a fork. I guess many distros are aware that there's a new version, but they're waiting for a signal that is stable or something.

**Pull request merged**
